title: GuTestIPA
description: 一个基于 GitHub 的测试下载平台
show_downloads: false

baseurl: "/GuTestIPA" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://guyari.github.io" # change this to the base hostname & protocol for your site

cayman-blog:
  date_format: "%b %-d, %Y"

theme: jekyll-theme-cayman

github_username: guyari
email: guyari@163.com



